spring:
  application:
    name: todo-backend
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/todoapp}
    username: ${SPRING_DATASOURCE_USERNAME:todouser}
    password: ${SPRING_DATASOURCE_PASSWORD:todopass}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

logging:
  level:
    com.todoapp: INFO
    org.springframework.web: INFO